plugins/redmine_dashboard/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match 'projects/:id/rdb/taskboard'        => 'rdb_taskboard#index',  :as => :rdb_taskboard,        via: [:get, :post]
match 'projects/:id/rdb/taskboard/move'   => 'rdb_taskboard#move',   :as => :rdb_taskboard_move,   via: [:get, :post]
match 'projects/:id/rdb/taskboard/update' => 'rdb_taskboard#update', :as => :rdb_taskboard_update, via: [:get, :post]
match 'projects/:id/rdb/taskboard/filter' => 'rdb_taskboard#filter', :as => :rdb_taskboard_filter, via: [:get, :post]


match 'projects/:id/rdb(/:board)'  => 'rdb_dashboard#index', :as => :rdb, via: [:get, :post]
match 'projects/:id/dashboard'     => 'rdb_dashboard#index', via: [:get, :post]

plugins/redmine_dashboard/app/models/rdb_dashboard.rb
class RdbDashboard
  attr_reader :project, :projects, :project_ids, :options

  VIEW_MODES = [ :card, :compact ]

  def initialize(project, opts, params = nil)
    @project     = project

    @options = { :filters => {} }

    options.merge! self.class.defaults
    options.merge! opts

    if params[:include_subprojects]
      options[:include_subprojects] = (params[:include_subprojects] == 'true')
    end

    reload_projects!

    # Init board in sub class
    init if respond_to? :init

    filters.each do |id, filter|
      filter.values = options[:filters][filter.id] if options[:filters][filter.id]
    end
  end

  def reload_projects!
    if options[:include_subprojects]
      @project_ids = subproject_ids([project.id])
    else
      @project_ids = [project.id]
    end
    @projects = Project.where :id => project_ids
  end

  def subproject_ids(ids)
    ids.inject(ids.dup) do |ids, id|
      ids + subproject_ids(Project.where(:parent_id => id).pluck(:id))
    end.uniq
  end

  def setup(params)
    # Update issue view mode
    options[:view] = params[:view].to_sym if params[:view] and RdbDashboard::VIEW_MODES.include? params[:view].to_sym
  end

  def update(params)
    if params[:reset]
      filters.each do |id, filter|
        filter.values = filter.default_values
      end
      options[:filters] = {}
    else
      filters.each do |id, filter|
        filter.update params if params
        options[:filters][filter.id] = filter.values
      end
    end
  end

  def issue_view
    options[:view]
  end

  def issues
    filter(Issue.where(:project_id => project_ids))
  end

  def versions
    Version.where :project_id => project_ids
  end

  def issue_categories
    IssueCategory.where :project_id => project_ids
  end

  def trackers
    Tracker.where(:id => projects.map{|p| p.trackers.pluck(:id)}.uniq.flatten)
  end

  def assignees
    Principal.where :id => member_principals.pluck(:user_id)
  end

  def members
    Member.where(:id => projects.map{|p| p.members.map(&:id)}.uniq.flatten)
  end

  def member_principals
    Member.where(:id=> projects.map{|p| p.member_principals.map(&:id)}.uniq.flatten)
  end

  def memberships
    Member.where(:id => projects.map{|p| p.memberships.pluck(:id) }.uniq.flatten)
  end

  def filter(issues)
    issues = filters.inject(issues) {|issues, filter| filter[1].scope issues }
    filters.inject(issues) {|issues, filter| filter[1].filter issues }
  end

  def abbreviation(project_id)
    project_id = project.id unless project_id

    @abbreviations ||= []
    @abbreviations[project_id] ||= begin
      abbreviation = '#'
      Project.find(project_id).custom_field_values.each do |f|
        abbreviation = f.to_s + '-' if f.to_s.length > 0 and f.custom_field.read_attribute(:name).downcase == 'abbreviation'
      end
      abbreviation
    end
  end

  def issue_id(issue)
    if issue.respond_to?(:issue_id)
      issue.issue_id
    else
      abbreviation(issue.project_id) + issue.id.to_s
    end
  end

  def id
    self.class.board_type
  end

  def name
    I18n.t :"rdb_#{id}"
  end

  def add_filter(filter)
    filter.board = self
    filters[filter.id.to_s] = filter
  end

  def add_group(group)
    group.board = self
    group_list << group
    groups[group.id.to_s] = group
  end

  def editable?(str = nil)
    @editable ||= !!User.current.allowed_to?(:edit_issues, project)
    str ? (@editable ? str : nil) : @editable
  end

  def filters; @filters ||= HashWithIndifferentAccess.new end
  def groups; @groups ||= HashWithIndifferentAccess.new end
  def group_list; @group_list ||= [] end

  class << self
    def board_type
      @board_type ||= name.downcase.to_s.gsub(/^rdb/, '').to_sym
    end

    def defaults
      @defaults ||= load_defaults
    end

    def load_defaults
      config = YAML.load_file File.expand_path('../../../config/default.yml', __FILE__)

      {
        view: check_opts(config, 'view', :card, :compact),
        include_subprojects: check_opts(config, 'include_subprojects', false, true),
        assignee: check_opts(config, 'assignee', :me, :all),
        version: check_opts(config, 'version', :latest, :all),
        hide_done: check_opts(config, 'hide_done', false, true),
        change_assignee: check_opts(config, 'change_assignee', false, true)
      }
    end

    def check_opts(options, name, *values)
      value = options.fetch(name) { return values.first }
      values.each do |val|
        return val if val == value || val.to_s == value
      end

      values.first
    end
  end
end

plugins/redmine_dashboard/app/controllers/rdb_dashboard_controller.rb
class RdbDashboardController < ApplicationController
  unloadable
  menu_item :dashboard
  before_filter :find_project, :authorize
  before_filter :setup_board, :except => :index
  before_filter :find_issue, :only => [ :move, :update ]
  before_filter :authorize_edit, :only => [ :move, :update ]
  after_filter :save_board_options

  def index
    return redirect_to rdb_taskboard_url if params[:controller] == 'rdb_dashboard'
    setup_board params
  end

  def filter
    @board.update params
    render :action => 'index'
  end

  def update
    render_404
  end

  def move
    render_404
  end

private
  def board_type; nil end

  def board
    clazz = board_type
    clazz.new(@project, options_for(clazz.name), params) if clazz
  end

  def setup_board(params = nil)
    return render_404 unless @board = board
    @board.setup params if params
    @board.build
    @board
  end

  def save_board_options
    save_options_for(@board.options, self.board_type.name) if @board
  end

  def authorize_edit
    raise Unauthorized.new unless User.current.allowed_to?(:edit_issues, @project)
  end

  def find_project
    @project = Project.find params[:id]
  end

  def find_issue
    flash_error :rdb_flash_missing_lock_version and return false unless params[:lock_version]

    @issue = Issue.find params[:issue]

    if @issue.lock_version != params[:lock_version].to_i
      flash_error :rdb_flash_stale_object, :update => true, :issue => @issue.subject
      return false
    end

    @issue.lock_version = params[:lock_version].to_i
    @issue
  end

  def flash_error(sym, options = {})
    flash.now[:rdb_error] = I18n.t(sym, options).html_safe
    Rails.logger.info "Render Rdb flash error: #{sym}"
    options[:update] ? render('index.js') : render('error.js')
  end

  def options_for(board)
    session["dashboard_#{@project.id}_#{User.current.id}_#{board}"] ||= {}
  end

  def save_options_for(options, board)
    session["dashboard_#{@project.id}_#{User.current.id}_#{board}"] = options
  end

  def session_id
    "dashboard_#{@project.id}_#{User.current.id}"
  end
end

plugins/redmine_dashboard/app/helpers/rdb_dashboard_helper.rb
module RdbDashboardHelper

  def render_rdb_menu(id, title, options = {}, &container)
    options[:class] ||= ''
    options[:class] += ' rdb-menu-right' if options[:right]
    options[:class] += ' rdb-small' if options[:small]

    haml_tag :div, :class => "rdb-menu rdb-menu-#{id} #{options[:class]}" do
      if options[:anchor]
        link = options[:anchor].call.to_s.html_safe
      else
        link = link_to(title, '#', :class => 'rdb-menu-link')
      end

      if options[:header] and [:h1, :h2, :h3, :h4, :h5].include? options[:header].to_sym
        haml_concat content_tag(options[:header], link)
      else
        haml_concat link
      end

      haml_tag :div, :class => "rdb-container #{options[:right] ? 'rdb-container-right' : ''}" do
        haml_tag :div, :class => "rdb-container-wrapper #{options[:icons] ? 'rdb-icons' : ''}" do
          if options[:inlet]
            haml_tag :div, :class => 'rdb-container-inlet' do
              container.call
            end
          else
            container.call
          end
        end
      end
    end
  end

  def render_rdb_menu_list(items = nil, options = {}, &block)
    options, items = items, nil if items.is_a?(Hash)
    haml_tag :div, :class => "rdb-list #{options[:async] ? 'rdb-async' : ''} #{options[:class]}" do
      haml_tag :h3, options[:title] if options[:title]
      haml_tag options[:list_tag] ? options[:list_tag] : :ul, :class => options[:list_class] do
        if items
          items.each do |item|
            haml_tag :li do
              block.call item
            end
          end
        else
          block.call
        end
      end
    end
  end

  def render_rdb_menu_list_item(options = {}, &block)
    haml_tag :li, :class => options[:async] ? 'rdb-async' : '' do
      block.call
    end
  end

  def rdb_checkbox_link_to(*args)
    options = args.extract_options!
    options[:class] ||= ''
    options[:class] += ' rdb-checkbox-link'
    options[:class] += ' rdb-checkbox-link-enabled' if options[:enabled]
    options[:class] += ' rdb-checkbox-link-disabled' if !options[:enabled] && options[:show_disabled]
    options[:class].strip!

    options.delete :enabled
    options.delete :show_disabled

    args << options

    link_to *args
  end

  def rdb_update_path(issue, options = {})
    send(:"rdb_#{@board.id}_update_path", {
      :issue => issue.id,
      :lock_version => issue.lock_version
    }.merge(options))
  end

  def rdb_move_path(issue, options = {})
    send(:"rdb_#{@board.id}_move_path", {
      :issue => issue.id,
      :lock_version => issue.lock_version
    }.merge(options))
  end

  def rdb_filter_path(options = {})
    send(:"rdb_#{@board.id}_filter_path", options)
  end

  def rdb_board_path(options = {})
    send(:"rdb_#{@board.id}_path", options)
  end
end

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_column.html.haml
- if issues.any? and @board.groups.count > 1
  %div.rdb-column-head=t :rdb_x_issues, :count => issues.count
- grouped_issues = issues.group_by{|i| i.priority.position}
- grouped_issues.keys.sort.reverse.each do |priority|
  - grouped_issues[priority].sort_by(&:id).each do |issue|
    = render :partial => 'rdb_dashboard/issues/issue', :locals => { :issue => issue, :group => group }

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_column_dialog.html.haml
%div
  %div.rdb-card.rdb-card-dialog
    %div{:class => "rdb-priority rdb-priority-#{@issue.priority.position}" }
      %header.rdb-card-header
        %span.rdb-card-title
          = link_to "#{@board.abbreviation(@issue.project_id)}#{@issue.id}", @issue

      %div.rdb-card-progress
        %div.rdb-card-progress-bar{:style => "width: #{@issue.done_ratio}%;" }

      %div.rdb-card-content
        %div.rdb-card-subject.rdb-property-subject= @issue.subject

      %div.rdb-card-dialog-box.rdb-async
        %label=t :rdb_dialog_update_issue_status
        %ul
          - @statuses.each do |status|
            %li
              = link_to status.name, rdb_update_path(@issue, :status => status.id)

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_column_names.html.haml
%ul.rdb-headers
  - @board.column_list.each do |column|
    - if column.visible?
      %li.rdb-column{:class => column.compact? ? 'rdb-column-compact' : ''}
        %h3= column.title
        - if column.issues.count > 0
          %span= t :rdb_x_issues, :count => column.issues.count

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_columns.html.haml
%ul.rdb-columns
  - @board.visible_columns.each do |column|
    %li.rdb-column{:class => column.compact? ? 'rdb-column-compact' : '', :data => {:'rdb-column-id' => column.id, :'rdb-drop-group' => group.id}}
      - if not column.compact?
        = render :partial => 'rdb_dashboard/taskboard/column', :locals => { :column => column, :issues => group.filter(column.issues), :group => group }

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_group.html.haml
.rdb-group{:data => {:'rdb-group-id' => group.id}}
  .rdb-group-header
    %a.rdb-evt-group-toggle
      %h4= group.title
      %span= t :rdb_x_issues, :count => group.issue_count
  = render :partial => 'rdb_dashboard/taskboard/columns', :locals => { :group => group }

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_groups.html.haml
.rdb-groups
  - if @board.groups.count == 1
    .rdb-group{:data => {:'rdb-group-id' => @board.group_list.first.id}}
      = render :partial => 'rdb_dashboard/taskboard/columns', :locals => { :group => @board.group_list.first }
  - else
    - show_all = @board.group_list.select(&:visible?).any? ? false : true
    - @board.group_list.each do |group|
      - if show_all or group.visible?
        = render :partial => 'rdb_dashboard/taskboard/group', :locals => { :group => group }

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_header.html.haml
.rdb-board
  = link_to '', rdb_board_path, :class => "rdb-async", :id => "rdb-refresh"

  - render_rdb_menu :board, @board.name, :header => :h2 do
    - render_rdb_menu_list [:taskboard] do |val|
      = link_to t("rdb_#{val}"), rdb_path(:board => val)

- if @board.versions.any?
  .rdb-filter.rdb-async
    - render_rdb_menu :versions, @board.filters[:version].title do
      - render_rdb_menu_list [:all, :unassigned] do |val|
        = link_to t("rdb_filter_version_#{val}"), rdb_filter_path(:version => val)
      - render_rdb_menu_list @board.filters[:version].versions do |val|
        = link_to val.name, rdb_filter_path(:version => val.id)

.rdb-filter.rdb-async
  - render_rdb_menu :tracker, @board.filters[:tracker].title, :icons => true do
    - render_rdb_menu_list [:all] do |val|
      = link_to t("rdb_filter_tracker_#{val}"), rdb_filter_path(:tracker => val)
    - render_rdb_menu_list @board.trackers do |val|
      %span.rdb-multicheck
        = rdb_checkbox_link_to '', rdb_filter_path(:tracker => val.id), :enabled => @board.filters[:tracker].enabled?(val.id), :show_disabled => true
        = link_to val.name, rdb_filter_path(:tracker => val.id, :only => true)

- if @board.issue_categories.any?
  .rdb-filter.rdb-async
    - render_rdb_menu :categories, @board.filters[:category].title, :icons => true do
      - render_rdb_menu_list [:all] do |val|
        = link_to t("rdb_filter_category_#{val}"), rdb_filter_path(:category => val)
      - render_rdb_menu_list @board.issue_categories do |val|
        %span.rdb-multicheck
          = rdb_checkbox_link_to '', rdb_filter_path(:category => val.id), :enabled => @board.filters[:category].enabled?(val.id), :show_disabled => true
          = link_to val.name, rdb_filter_path(:category => val.id, :only => true)

.rdb-filter.rdb-async
  - render_rdb_menu :assignee, @board.filters[:assignee].title do
    - render_rdb_menu_list [:all, :me, :none] do |val|
      = link_to t("rdb_filter_assignee_#{val}"), rdb_filter_path(:assignee => val)
    - render_rdb_menu_list @board.assignees do |val|
      - if User === val
        = link_to val.name, rdb_filter_path(:assignee => val.id)
    - render_rdb_menu_list @board.assignees do |val|
      - if Group === val
        = link_to val.name, rdb_filter_path(:assignee => val.id)

.rdb-option.rdb-async
  - render_rdb_menu :options, t(:rdb_options), :right => true, :icons => true do
    - render_rdb_menu_list do
      - render_rdb_menu_list_item do
        = rdb_checkbox_link_to t(:rdb_options_change_assignee), rdb_board_path(:change_assignee => !@board.options[:change_assignee]),
            :enabled => @board.options[:change_assignee], :title => t(:rdb_options_change_assignee_info)
        = rdb_checkbox_link_to t(:rdb_options_hide_done), rdb_board_path(:hide_done => !@board.options[:hide_done]),
            :enabled => @board.options[:hide_done], :title => t(:rdb_options_hide_done_info)
        = rdb_checkbox_link_to t(:rdb_options_include_subprojects), rdb_board_path(:include_subprojects => (@board.project_ids.size > 1) ? 'false' : 'true'),
            :enabled => (@board.project_ids.size > 1)
    - render_rdb_menu_list @board.column_list, :title => t(:rdb_options_columns) do |column|
      = rdb_checkbox_link_to column.title, rdb_board_path(:column => column.id), :enabled => @board.columns[column.id].visible?
    - render_rdb_menu_list do
      - render_rdb_menu_list_item do
        = link_to t(:rdb_options_fullscreen), 'javascript:Rdb.rdbToggleFullscreen();', :id => "rdb-option-fullscreen"
      -#- render_rdb_menu_list_item do
      -#  = link_to t(:rdb_options_configure), rdb_configure_path, :id => "rdb-configure", :class => 'rdb-sync'
      - render_rdb_menu_list_item do
        = link_to t(:rdb_options_reset), rdb_filter_path(:reset => 1), :id => "rdb-reset", :title => t(:rdb_options_reset_info)

.rdb-option.rdb-async
  - render_rdb_menu :view, t(:rdb_options_view), :right => true do
    - render_rdb_menu_list RdbDashboard::VIEW_MODES, :title => t(:rdb_options_issue_view) do |view|
      = rdb_checkbox_link_to t(:"rdb_options_issue_view_#{view}"), rdb_board_path(:view => view), :enabled => @board.options[:view] == view
    -#- render_rdb_menu_list RdbDashboard::BOARD_MODES, :title => t(:rdb_options_board_view) do |mode|
    -#  = rdb_checkbox_link_to t(:"rdb_options_board_view_#{mode}"), rdb_board_path(:mode => mode), :enabled => @board.options[:mode] == mode
    -#- if @board.compact?
    - render_rdb_menu_list [:none, :tracker, :category, :priority, :assignee, :version, :parent, :project], :title => t(:rdb_options_group) do |group|
      = rdb_checkbox_link_to t(:"rdb_group_#{group}"), rdb_board_path(:group => group), :enabled => @board.options[:group] == group

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_overall_progress.html.haml
%div.rdb-overall-progress
  - @board.column_list[0..-2].each do |column|
    %a.rdb-overall-progress{:class => "rdb-column-#{column.id}", :style => "width: #{column.percentage}%"}

plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/column_dialog.js.erb
$().rdbDialog("<%= escape_javascript t(:rdb_dialog_update_issue_title) %>", "<%= escape_javascript(render :partial => 'rdb_dashboard/taskboard/column_dialog') %>");